services:
  frontend:
    build:
      context: ./front-end
      dockerfile: Dockerfile
    ports:
      - "3000:80"
    depends_on:
      - nlp

  nlp:
    build:
      context: ./nlpModel
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
