version: '3.9'

services:
  frontend:
    build: ./front-end
    ports:
      - "3000:80"

  backend:
    build: ./back-end
    ports:
      - "8080:8080"

  nlp:
    build: ./nlpModel
    ports:
      - "5000:5000"
